"""
Django settings for Stephanos_Estetic project.
Generated by 'django-admin startproject' (Django 5.2.6).
"""

# ──────────────────────────────────────────────────────────────────────────────
# Imports & Paths
# ──────────────────────────────────────────────────────────────────────────────
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent  # carpeta raíz (donde está manage.py)

# Cargar variables de entorno desde .env en la raíz del proyecto
load_dotenv(BASE_DIR / ".env")

# ──────────────────────────────────────────────────────────────────────────────
# Core / Seguridad
# ──────────────────────────────────────────────────────────────────────────────
SECRET_KEY = "django-insecure-a*ei31nk+g*tw@=*i588z2%h(w)1@e*a%$0ebbrkn$#0l^q$t%"  # cambia en prod
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# ──────────────────────────────────────────────────────────────────────────────
# Apps
# ──────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Terceros
    "rest_framework",
    "corsheaders",
    "import_export",

    # Auth sites/allauth
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    # Proyecto
    "SE_sales",
    "SE_services",
    "SE_contact",
    "SE_payments",
    "SE_users",
]

# ──────────────────────────────────────────────────────────────────────────────
# Middleware
# ──────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Stephanos_Estetic.urls"
WSGI_APPLICATION = "Stephanos_Estetic.wsgi.application"

# ──────────────────────────────────────────────────────────────────────────────
# Templates
# ──────────────────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# Base de datos
# ──────────────────────────────────────────────────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ──────────────────────────────────────────────────────────────────────────────
# Passwords
# ──────────────────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ──────────────────────────────────────────────────────────────────────────────
# I18N / TZ
# ──────────────────────────────────────────────────────────────────────────────
LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# ──────────────────────────────────────────────────────────────────────────────
# Static
# ──────────────────────────────────────────────────────────────────────────────
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────────────────────────────────────
# CORS / CSRF (SPA Vite en 5173 y backend en 8000)
# ──────────────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Cookies en desarrollo (ajusta para producción con HTTPS)
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
CORS_ALLOW_CREDENTIALS = True

# Mantén los slashes de Django
APPEND_SLASH = True

# ──────────────────────────────────────────────────────────────────────────────
# DRF
# ──────────────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
        "contact_form": "5/hour",
    },
}

# ──────────────────────────────────────────────────────────────────────────────
# Auth / allauth
# ──────────────────────────────────────────────────────────────────────────────
SITE_ID = 1

# allauth: solo login social (Google)
ACCOUNT_SIGNUP_FIELDS         = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS         = {'email'}
SOCIALACCOUNT_LOGIN_ON_GET    = True
ACCOUNT_LOGOUT_ON_GET         = True
ACCOUNT_EMAIL_VERIFICATION    = "none"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}


# Logging de allauth en desarrollo
LOGGING = {
    "version": 1,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "allauth": {"handlers": ["console"], "level": "DEBUG"},
        "allauth.socialaccount": {"handlers": ["console"], "level": "DEBUG"},
        "django.request": {"handlers": ["console"], "level": "ERROR"},
    },
}

LOGIN_REDIRECT_URL = "http://localhost:5173/profile"
LOGOUT_REDIRECT_URL = "http://localhost:5173"

# Esto es para producción con HTTPS
'''SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
DEBUG = False
ALLOWED_HOSTS = ["tu-dominio.cl"]'''


# ──────────────────────────────────────────────────────────────────────────────
# Constantes del proyecto
# ──────────────────────────────────────────────────────────────────────────────
FRONTEND_URL = "http://localhost:5173"

WEBPAY_ENV = os.getenv("WEBPAY_ENV", "TEST")
WEBPAY_COMMERCE_CODE = os.getenv("WEBPAY_COMMERCE_CODE", "")
WEBPAY_API_KEY = os.getenv("WEBPAY_API_KEY", "")
WEBPAY_RETURN_URL = "http://localhost:8000/api/payments/commit"

# -----------------------------------------------------------------------------
# Configuración para reservas de servicios
# -----------------------------------------------------------------------------
# URL base del sitio (backend) utilizado al construir enlaces de retorno de Webpay.
# Ajusta en producción según tu dominio real, ej. "https://api.tu-dominio.cl"
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

# Correo donde la pyme recibirá las notificaciones de reservas. Debe definirse
# como variable de entorno BOOKING_NOTIFY_EMAIL o en settings.
BOOKINGS_NOTIFY_EMAIL = os.getenv("BOOKINGS_NOTIFY_EMAIL", "stephanosestetic@gmail.com")

# Ubicación utilizada en los archivos .ics (se mostrará en los calendarios)
BOOKING_LOCATION = os.getenv("BOOKING_LOCATION", "Stephanos Estetic - Santiago")

# Configuración para Google Calendar (service account). Para activar el envío de
# eventos automáticos al calendario de la empresa, establece GOOGLE_CALENDAR_SERVICE_ENABLED
# en True y define GOOGLE_CALENDAR_CALENDAR_ID y GOOGLE_CREDENTIALS_FILE.
GOOGLE_CALENDAR_SERVICE_ENABLED = os.getenv("GOOGLE_CALENDAR_SERVICE_ENABLED", "False") == "True"
GOOGLE_CALENDAR_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_CALENDAR_ID", "")
GOOGLE_CREDENTIALS_FILE = os.getenv("GOOGLE_CREDENTIALS_FILE", "")

# Google OAuth (alias por compatibilidad si en algún punto lees GOOGLE_OAUTH_CLIENT_ID)
GOOGLE_CLIENT_ID = (
    os.getenv("GOOGLE_OAUTH_CLIENT_ID")
    or os.getenv("GOOGLE_CLIENT_ID")
    or ""
)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "stephanosestetic@gmail.com")  # tu correo
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")  # app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 30

