# Generated by Django 5.2.6 on 2025-10-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
