# Generated by Django 5.2.6 on 2025-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_services', '0003_service_image_service_image_url_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='SE_services_provide_195625_idx',
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['starts_at', 'service'], name='SE_services_starts__8b3733_idx'),
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
