# Generated by Django 5.2.6 on 2025-11-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_services', '0004_remove_serviceprovider_user_remove_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
