# Generated by Django 5.2.6 on 2025-10-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
