# Generated by Django 5.2.6 on 2025-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
