# Generated by Django 5.2.6 on 2025-10-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=32),
        ),
    ]
