# Generated by Django 5.2.6 on 2025-11-01 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0007_order_paid_at_order_status'),
        ('SE_services', '0005_booking_deposit_amount_booking_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price_at', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='SE_sales.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SE_services.service')),
            ],
            options={
                'ordering': ['order_id', 'id'],
                'indexes': [models.Index(fields=['order'], name='SE_sales_se_order_i_37f6f2_idx'), models.Index(fields=['service'], name='SE_sales_se_service_1b2d8c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='serviceorderitem_qty_gt_0'), models.CheckConstraint(condition=models.Q(('price_at__gte', 0)), name='serviceorderitem_price_at_gte_0'), models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='serviceorderitem_line_total_gte_0')],
            },
        ),
    ]
