# Generated by Django 5.2.6 on 2025-11-14 19:06
from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    Product = apps.get_model("SE_sales", "Product")

    for product in Product.objects.all():
        # Si ya tiene slug por alguna razón, respétalo
        if getattr(product, "slug", None):
            continue

        base = slugify(product.name or product.sku or "producto")
        if not base:
            base = "producto"

        cand = base
        i = 1
        # evitar colisiones
        while Product.objects.filter(slug=cand).exclude(pk=product.pk).exists():
            cand = f"{base}-{i}"
            i += 1

        product.slug = cand
        product.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0008_serviceorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="products/", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            # IMPORTANTE: aquí SIN unique y permitiendo blank
            field=models.SlugField(max_length=140, blank=True),
        ),
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, blank=True),
        ),
    ]
