# Generated by Django 5.2.6 on 2025-11-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0009_product_image_product_image_url_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
