# Generated by Django 5.2.6 on 2025-11-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0011_product_slug'),
        ('SE_sales', '0012_auto_20251114_1613'),
    ]

    operations = [
    ]
