# Generated by Django 5.2.6 on 2025-09-27 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUIRES_ACTION', 'Requires Action'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('ref_object_id', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=30)),
                ('provider_session_id', models.CharField(blank=True, max_length=120)),
                ('return_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
