# Generated by Django 5.2.6 on 2025-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentintent',
            name='cancel_url',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='provider_session_id',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='ref_content_type',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='ref_object_id',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='return_url',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='accounting_date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='buy_order',
            field=models.CharField(db_index=True, default='DEFAULT_BUY_ORDER', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='installments_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_type_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='raw',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='token',
            field=models.CharField(db_index=True, default='temp_order', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='vci',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted'), ('REVERSED', 'Reversed')], max_length=16),
        ),
    ]
