# Generated by Django 5.2.6 on 2025-10-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_payments', '0002_remove_paymentintent_cancel_url_and_more'),
        ('SE_sales', '0007_order_paid_at_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='SE_sales.order'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted'), ('REVERSED', 'Reversed'), ('PENDING', 'Pending')], default='PENDING', max_length=16),
        ),
    ]
