# Generated by Django 5.2.6 on 2025-10-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_users', '0002_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
