# Generated by Django 5.2.6 on 2025-10-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE_sales', '0006_order_user'),
        ('SE_users', '0003_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SE_sales.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='SE_users_us_user_id_d94d62_idx'), models.Index(fields=['order'], name='SE_users_us_order_i_a921f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'order'), name='uix_user_order_history')],
            },
        ),
    ]
